### ISSUE TITLE
Installation of yast2 required?

### ISSUE THREAD

**Issue by gabi2** [yast/ycp-killer#443] opened 2013-06-10 09:46 UTC
I got an error from CommandLine.ycp when starting 'yast2 fcoe-client'  and same with 'yast2 audit-laf:

<1> e235(21262) [YCP] CommandLine.ycp:1360 Command line interface started
<3> e235(21262) [Interpreter] CommandLine.ycp:1387 Can't convert value '&lt;YCPRef:any ruby_reference ()&gt;' to type 'symbol ()'

Installed packages:
yast2-core-2.24.0-15.1.x86_64
yast2-ruby-bindings-1.0.0-39.1.x86_64
yast2-ycp-ui-bindings-2.21.6-2.2.x86_64
yast2-fcoe-client-2.22.4-8.1.noarch
yast2-audit-laf-2.24.0-12.1.noarch

The error is gone after installing  yast2-2.24.1-8.1.x86_64.

**Comment by jreidinger** [comment] 2013-06-10 09:52
Thanks for report. I need to investigate it why reference type is not one I expect.

**Comment by jreidinger** [comment] 2013-06-10 09:59
I investigate it and looks like bug in builtin is which say that reference is type of symbol() but reference is correctly type any(). I will check it.

**Comment by jreidinger** [comment] 2013-06-10 10:23
Problem is in `is` builtin. I fixing function reference comparison that was wrong in https://github.com/yast/yast-core/commit/720f906966143c7c50aaa7d12e36f2a8b35e82fc but looks like is builtin use it incorrect - https://github.com/yast/yast-core/blob/master/libycp/src/YExpression.cc#L1629 because it match value against type, but it should call if type match value.
There is bug also in old core.
Try e.g.

```
{
  symbol t(any i)
{
  return `a;
}

if (is(t, any(integer)))
{
  y2milestone("Matching");
} else {
  y2milestone("Problem, I wanna pass int and get anything and function accept anything and return symbol.");
}

}
```

**Comment by jreidinger** [comment] 2013-06-20 20:33
Should be fixed now. Please reopen if you can still reproduce it. Thanks

**Closed as completed by jreidinger** 2013-06-20 20:33 UTC
