### ISSUE TITLE
/sbin/yast2 firewall won't start

### ISSUE THREAD

**Issue by jirislaby** [yast/ycp-killer#418] opened 2013-05-31 11:27 UTC
It just does nothing.

y2log says:
2013-05-31 13:26:47 <3> anemoi(18264) [Ruby] ycp/wfm.rb:85 Client call failed with undefined method `textdomain' for YCP::Builtins:Module and backtrace ["/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:656:in`dgettext'", "/usr/share/YaST2/modules/SuSEFirewallServices.rb:82:in `block (2 levels) in ReadServicesDefinedByRPMPackages'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:95:in`call'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:95:in `block in foreach'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:94:in`each'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:94:in `foreach'", "/usr/share/YaST2/modules/SuSEFirewallServices.rb:77:in`block in ReadServicesDefinedByRPMPackages'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:86:in `call'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:86:in`block in foreach'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:85:in `each'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:85:in`foreach'", "/usr/share/YaST2/modules/SuSEFirewallServices.rb:49:in `ReadServicesDefinedByRPMPackages'", "/usr/share/YaST2/modules/SuSEFirewall.rb:1246:in`Read'", "/usr/share/YaST2/clients/firewall.rb:89:in `ReadDialog'", "/usr/share/YaST2/clients/firewall.rb:1620:in`block in FirewallSequence'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:501:in `call'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/builtins.rb:501:in`eval'", "/usr/share/YaST2/modules/Sequencer.rb:179:in `WS_run'", "/usr/share/YaST2/modules/Sequencer.rb:237:in`Run'", "/usr/share/YaST2/clients/firewall.rb:1630:in `FirewallSequence'", "/usr/share/YaST2/clients/firewall.rb:71:in`main'", "/usr/share/YaST2/clients/firewall.rb:1663:in `<top (required)>'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/wfm.rb:83:in`eval'", "/usr/lib64/ruby/vendor_ruby/1.9.1/ycp/wfm.rb:83:in `run_client'"]

**Comment by jreidinger** [comment] 2013-05-31 11:55
thanks for report. It is caused by not well coordinated move of method from class to instance one. Should be fixed now with recent packages.

**Comment by jreidinger** [comment] 2013-05-31 12:14
fix hit now OBS now. thanks for report

**Closed as completed by jreidinger** 2013-05-31 12:14 UTC
