### ISSUE TITLE
Text mode yast menu freezing for ~2min at start up

### ISSUE THREAD

**Issue by vmoravec** [yast/ycp-killer#467] opened 2013-06-17 14:10 UTC
It's easy to reproduce by typing `yast` into the console. 
First appears the blue ncurses screen with static message "Loading modules.." and then it stands still for about 2 minutes.
I have default yast modules installed as set up by the M2 image.

Here is the y2log with Y2DEBUG=1: https://gist.github.com/vmoravec/63286f41f0bd44ff5a61

**Comment by lslezak** [comment] 2013-06-18 05:57
Some notes: the ncurses control center is implemented in YCP, there is `menu.ycp` client in `yast2` package. In contrast the Qt control panel is a standard C++ Qt application, independent of YaST, cannot be affected by changes in YaST.

The `menu.ycp` reads the desktop files, it seems that something (`deep_copy`?) slows it down.

As a temporary workaround we could simply keep it in YCP format, the control panel is very important part of YaST, 2 minutes startup time is not acceptable even for a testing release.

**Comment by jreidinger** [comment] 2013-06-18 08:05
I cannot reproduce it. @lslezak or @jsuchome  can you please try to reproduce it? For me start is fast and fine.

**Comment by jsuchome** [comment] 2013-06-18 08:18
For me, it also works correctly. I have openSUSE-Factory-RUBY-YAST-fullDVD-x86_64-Build0001-Media.iso

**Comment by vmoravec** [comment] 2013-06-18 08:20
I tested this on minimal install of M2 and it runs without this lag at start-up. I'm still having this problem on machine with Xfce. I'll investigate this further.

**Comment by vmoravec** [comment] 2013-06-18 09:30
I found out that the problem is the line 43 in modules/Desktop.rb:

``` ruby
ret = Builtins.dpgettext("desktop_translations", "/usr/share/locale", msgid)
```

Going to debug that more, will post the results then.

**Comment by vmoravec** [comment] 2013-06-18 13:51
The issue is that the builtin method `dpgettext` passes the arguments to the `FastGettext.add_text_domain`, which iterates over all directories in the path.
- details for the builtin implementation https://github.com/yast/yast-ruby-bindings/blob/master/src/ruby/ycp/builtins.rb#L684 
- and fastgettext internals: https://github.com/grosser/fast_gettext/blob/master/lib/fast_gettext/translation_repository/base.rb#L39 

On my machine it takes about 2 seconds to finish one method call for the dir `/usr/share/locale`. I think we would need some caching, any hints where would be the best place to put it to?

**Comment by lslezak** [comment] 2013-06-19 05:59
I'll look at it...

**Comment by lslezak** [comment] 2013-06-19 06:41
Fixed in https://github.com/yast/yast-ruby-bindings/pull/46, now it starts in about 2 seconds.

**Comment by lslezak** [comment] 2013-06-20 10:52
The pull request has been merged, closing.

**Closed as completed by lslezak** 2013-06-20 10:52 UTC
