### ISSUE TITLE
comments lost in translations

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#617] opened 2013-08-06 08:31 UTC
in the original ycp, there's a comment for each string in the map, see  https://github.com/yast/yast-ldap-client/commit/11418a2981234f78d261840d2fea19a9b0ab792e#L17L346

But in translated code, there's only one of them:
 https://github.com/yast/yast-ldap-client/blob/master/src/modules/Ldap.rb#L306

**Comment by dmajda** [comment] 2013-08-06 11:37
It seems that `ycpc` parser has problems with attaching comments to negative numbers. I extracted a minimal test case.

### YCP

``` ycp
{
  integer a =
    // comment
    1;

  integer b =
    // comment
    -1;
}
```

### Ruby

``` ruby
# encoding: utf-8

module Yast
  class DefaultClient < Client
    def main
      @a =
        # comment
        1

      @b = -1

      nil
    end
  end
end

Yast::DefaultClient.new.main
```

This is something for @jreidinger and @mvidner but since they are both on vacation, I'll try to dig more...

**Comment by dmajda** [comment] 2013-08-08 10:11
The root cause was a bug in YCP parser. I fixed it in https://github.com/yast/yast-core/issues/41.

I re-run the conversion with the fix and determined that the only occurrence of this problem was in `Ldap.rb`. I fixed it in https://github.com/yast/yast-ldap-client/issues/13.

Closing.

**Closed as completed by dmajda** 2013-08-08 10:11 UTC
