### ISSUE TITLE
Version.ycp not translated to rb

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#466] opened 2013-06-17 10:51 UTC
Part of yast2 package is Version.ycp file, even after conversion to ruby

**Comment by lslezak** [comment] 2013-07-15 13:43
The YCP killer looks for `*.ycp` and `*.yh` files. The problem is that `Version.ycp` is generated from `Version.ycp.in` file which is ignored during conversion.

The fix should be trivial.

**Comment by lslezak** [comment] 2013-07-15 14:11
Fixed in #555.

**Closed as completed by lslezak** 2013-07-15 14:11 UTC
