### ISSUE TITLE
yast2 language ends with "Client call failed"

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#412] opened 2013-05-31 07:44 UTC
On installed system, I tried to change language with 'yast2 language'. 
Selected Czech as primary and DE+EN as secondary. Everything seemed to work correctly, but in logs I see some errors:

```
2013-05-30 16:16:02 <3> linux-ldgn(2852) [Ruby] ycp/wfm.rb:85 Client call failed with divided by 0 and backtrace [
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/ops.rb:133:in `/'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/ops.rb:133:in `divide'",
     "/usr/share/YaST2/modules/PackageSlideShow.rb:462:in `UpdateTotalProgressValue'",
     "/usr/share/YaST2/modules/PackageSlideShow.rb:475:in `UpdateTotalProgress'",
     "/usr/share/YaST2/modules/PackageSlideShow.rb:599:in `SlideDisplayDone'",
     "/usr/share/YaST2/modules/SlideShowCallbacks.rb:250:in `DonePackage'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/fun_ref.rb:16:in `call'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/fun_ref.rb:16:in `call'",
     "(eval):2:in `call_ycp_function'",
     "(eval):2:in `PkgCommit'",
     "/usr/share/YaST2/modules/Language.rb:597:in `PackagesCommit'",
     "/usr/share/YaST2/clients/language.rb:47:in `LanguageWrite'",
     "/usr/share/YaST2/clients/language.rb:79:in `LanguageSequence'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/fun_ref.rb:16:in `call'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/fun_ref.rb:16:in `call'",
     "/usr/share/YaST2/modules/CommandLine.rb:876:in `Run'",
     "/usr/share/YaST2/clients/language.rb:22:in `main'",
     "/usr/share/YaST2/clients/language.rb:136:in `<top (required)>'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/wfm.rb:83:in `eval'",
     "/usr/lib64/ruby/vendor_ruby/2.0.0/ycp/wfm.rb:83:in `run_client'"
]
```

Sysconfig is saved correctly, not sure if language packages actually were installed (does not seem so).

**Comment by jsuchome** [comment] 2013-05-31 07:48
y2log is here: http://pastebin.suse.de/6976

**Comment by jsuchome** [comment] 2013-05-31 07:50
I tested with openSUSE-Factory-RUBY-YAST-fullDVD-x86_64-Build0002-Media.iso

**Comment by jreidinger** [comment] 2013-05-31 09:23
Looks like ycp survive division by zero but ruby bindings not. I will fix it, but still I think it is bug in Package slide show that should not do it.
@lslezak Do you have idea when it can happen?

**Comment by lslezak** [comment] 2013-05-31 16:35
Um, no idea why it can happen.

@jsuchome Could you reproduce it also in YCP YaST (13.1 M1)?

**Comment by lslezak** [comment] 2013-05-31 16:37
@jsuchome YCP logs `division by zero` into `y2log` so just try the same in YCP Yast and then check the log. Thanks!

**Comment by jsuchome** [comment] 2013-06-03 07:12
Indeed, there's division by zero reported from PackageSlideShow.ycp, several times - so it does not crash. First time:

2013-06-03 09:07:49 <3> linux-wxvq(5569) [Interpreter] PackageSlideShow.ycp:1045 division by zero

**Comment by lslezak** [comment] 2013-06-03 08:08
OK, thanks for the report, I'll try fixing it in master...

**Comment by jreidinger** [comment] 2013-06-03 08:20
@lslezak I also fix it in ruby bindings to simulate in 'divide' so fascinating behavior :)

**Comment by lslezak** [comment] 2013-06-03 14:16
Fixed in PackageSlideShow.ycp in https://github.com/yast/yast-packager/pull/12

**Comment by jreidinger** [comment] 2013-06-06 14:55
fixed in ruby bindings https://github.com/yast/yast-ruby-bindings/commit/e9dbc63b5552a97119247516e039dff04e3c4287

**Closed as completed by jreidinger** 2013-06-06 14:55 UTC
