### ISSUE TITLE
Endless loop for failing Pkg import

### ISSUE THREAD

**Issue by vmoravec** [yast/ycp-killer#507] opened 2013-07-02 08:50 UTC
Found during testing of wagon module in ncurses. The issue occured after libzypp has done its work and the update process started (or should start). It gets into some strange endless loop while the gui disappears.

The loop logs these lines hundreds times: http://pastebin.suse.de/7268

**Comment by vmoravec** [comment] 2013-07-02 08:57
Turned out I broke the system by letting wagon to break some package dependencies which caused zypper to get corrupt and unusable. The question is if this is an edge case for wagon and whether the logged exception has been handled correctly.

**Comment by jreidinger** [comment] 2013-07-02 09:07
Well, ycp stop earlier as parser respond that it cannot import `Pkg` namespace. Question is if we can do it also in same speed and what cause endless loop, as it should catch exception and stop

**Comment by vmoravec** [comment] 2013-07-08 14:18
I re-tested the recent wagon package and this issue does not occur there anymore, not sure what would be the specific use case then. Changed the title of the issue to make it more appropriate.

**Comment by lslezak** [comment] 2013-07-16 07:13
Um, I could not reproduce it with the latest packages from Y:H:r, I removed `libzypp.so.1200` and `libzypp.so` symlink to trigger the same error, tested `sw_single` and `repositories` clients and I got 

```
[liby2] Y2PluginComponent.cc(loadPlugin):234 error loading plugin
/usr/lib64/YaST2/plugin/libpy2Pkg.so.2: libzypp.so.1200: cannot open shared object file:
No such file or directory
[Interpreter] :0 Loading module 'Pkg' failed
[libycp] Import.cc(import):97 No matching component found
[Ruby] binary/Yast.cc(getNs):67 ruby call: Can't import namespace 'Pkg'
```

but the clients finished correctly without any endless loop.

Closing as WORKSFORME :wink:

**Closed as completed by lslezak** 2013-07-16 07:13 UTC
